FROM alpine

RUN apk update ;\ 
    apk add --no-cache wget libc6-compat;\
    apk add openssl ;\
    wget https://dl.grafana.com/oss/release/grafana-7.1.5.linux-amd64.tar.gz -P /tmp;\
    tar -zxvf /tmp/grafana-7.1.5.linux-amd64.tar.gz -C /root;\
    rm -f /tmp/grafana-7.1.5.linux-amd64.tar.gz;\
    mv /root/grafana-7.1.5 /root/grafana

RUN mkdir -p /var/lib/grafana/dashboards

ADD ./my_dashboards/* /var/lib/grafana/dashboards/
ADD ./dashboard.yaml /root/grafana/conf/provisioning/dashboards
ADD ./datasources.yaml /root/grafana/conf/provisioning/datasources

WORKDIR /root/grafana/
EXPOSE 3000
CMD ./bin/grafana-server 