apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"  # pour que métallb utilise une ip pour tout les services
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 21
    name: ftps
  - port: 20
    name: ftps-20
  - port: 30000
    name: ftps-30000
  - port: 30001
    name: ftps-30001
  - port: 30002
    name: ftps-30002
  - port: 30003
    name: ftps-30003
  - port: 30004
    name: ftps-30004
  - port: 30005
    name: ftps-30005
  - port: 30006
    name: ftps-30006
  - port: 30007
    name: ftps-30007
  - port: 30008
    name: ftps-30008
  - port: 30009
    name: ftps-30009
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30000
        - containerPort: 30001
        - containerPort: 30002
        - containerPort: 30003
        - containerPort: 30004
        - containerPort: 30005
        - containerPort: 30006
        - containerPort: 30007
        - containerPort: 30008
        - containerPort: 30009
        env:
        - name: USER
          value: naila
        - name: PASSWORD
          value: naila1234